version: '3.9' 
services: 
    mysql: 
        image: mysql:5.7 
        container_name: mysql 
        command: --default-authentication-plugin=mysql_native_password 
        restart: always 
        environment: 
           MYSQL_DATABASE: techfood 
           MYSQL_ROOT_USER: root 
           MYSQL_ROOT_PASSWORD: urubu100 
        networks: 
          - compose-bridge 
        ports: 
          - "3306:3306" 
        expose:  
          - "3306" 
 
networks: 
    compose-bridge: 
        driver: bridge